### ISSUE TITLE
h('meta').outerHTML

### ISSUE THREAD

**Issue by uufish** [hyperhype/hyperscript#47]
```
h('meta').outerHTML // on the server
```

This code output `<meta></meta>`, but it is not good. What should I do.

**Comment by dominictarr** [comment]
what should it output? even if it expects a closing tag this still probably works.

**Comment by reqshark** [comment]
outerHTML would reach parent tags of `<body>` and `<head>` and calling outerHTML on their parents?

in fact with outerHTML i could set grandparent tags on the doctype

**Comment by dominictarr** [comment]
@reqshark that isn't how outerHTML works, it doesn't touch any parent elements, just the current tag. the it's just innerHTML (the children of that tag) surrounded by the tag itself.

**Comment by reqshark** [comment]
ah ok, so `outerHTML` isn't about the parent, @dominictarr thanks for clarifying!

**Comment by thirdhand** [comment]
I think this has to do with the fact that the version of html-element that is the dependency in npm still is ~1.3.0, while before 1.4.0 it didn't handle self closing tags. This is actually already fixed in the commit fixing #24, it just isn't pushed to npm yet. I just got bitten by this as well.

**Comment by sakanabiscuit** [comment]
Thanks. It was my misunderstanding.
