### ISSUE TITLE
move to org

### ISSUE THREAD

**Issue by dominictarr** [hyperhype/hyperscript#61]
There are now quite a few things in the hyperscript world.
I think we should move to an org. on the one hand, this means that users can easily see the collection of modules in the ecosystem, that work well together, but also, it becomes possible to add people as _administrators_. Otherwise, the original maintainer is the only person who can add more collaborators, but in an org, admins can add other admins, which means the community can become self-sustaining.

I would also add some things https://github.com/dominictarr/hyperlightbox
https://github.com/dominictarr/hypertabs and probably some other stuff...

@clehner @ahdinosaur @mixmix good idea?

**Comment by dominictarr** [comment]
I made an org here: http://github.com/hyperhype

**Comment by mixmix** [comment]
Nice!

**Comment by ahdinosaur** [comment]
sounds good to me :+1:
