### ISSUE TITLE
Consider adding Emmet-style syntactic sugar

### ISSUE THREAD

**Issue by EvgenyOrekhov** [hyperhype/hyperscript#72]
[HtmlElement](https://github.com/spatie/html-element) PHP library is based on HyperScript, but it also adds some [Emmet](https://emmet.io/)-style syntactic sugar, in particular the `>` operator.

It would allow to rewrite the following nested elements

```js
h(
    "div#page",
    h(
        "div#header",
        h("h1.classy", "h", { style: {"background-color": "#22f"} })
    )
);
```

like this

```js
h(
    "div#page > div#header > h1.classy",
    "h",
    { style: {"background-color": "#22f"} }
);

```

What's your opinion on this feature?

**Comment by EvgenyOrekhov** [comment]
I guess there is no need in integrating this feature into HyperScript as it turned out to be pretty easy to implement it as a wrapper: https://github.com/EvgenyOrekhov/emmet-hyperscript/blob/master/src/index.js.

Not closing the issue yet, still want to hear some feedback.

**Comment by brodybits** [comment]
@EvgenyOrekhov I really like your idea to support higher-level style "sugar" in a separate, higher-level wrapper component.

**Comment by EvgenyOrekhov** [comment]
Use this if you need Emmet-style syntactic sugar: https://github.com/EvgenyOrekhov/emmet-hyperscript.

**Comment by dominictarr** [comment]
@EvgenyOrekhov that's neat! It's definitely better to have this in a module. we are not adding new features to hyperscript. It's better to keep it simple.

Also, personally I'm wary of syntactic sugar. It saves a few key strokes but makes it more complicated and less obvious. I think simplicity is more important than convenience, see my comment here on [depnest - electric can opener](https://github.com/depject/depject/issues/19#issuecomment-279216372)
